title: "WebApplications Lecture Homepage"
author: "Markus Huber, Florian Rappl"
email: "mail@florian-rappl.de"
description: "Official website of the WebApplications lecture of the University of Regensburg."
keywords: "Lecture, HTML5, CSS3, JavaScript, Web, WebApp, JSON, Regensburg, University"
url: "http://webapplecture.github.io"
more: "read more"
favicon: "/images/favicon.ico"
excerpt_separator: "\n\n\n"
markdown: kramdown
highlighter: pygments
paginate: 5
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: false}}]
